import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";

import "@mantine/core/styles.css";

import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { NavbarNested } from "@/components/ui/NavbarNested/NavbarNested";
import Header from "@/components/dashboard/header/Header";
import { useAuthStore } from "@/stores/useAuthStore";
import { redirect } from "next/navigation";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${nunitoSans.className} antialiased flex min-h-screen max-w-screen`}
      >
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
